### PR TITLE
Added typescript support

### PR DESCRIPTION
**Pull request by CanTheAlmighty**
Included a new `index.d.ts` for Typescript and README note about it.

I tried to create it as closely as possible as the definition in the library and the REST API.

### CODE REVIEW

**Comment by se-bastiaan** [comment]
Since this has not been merged so far, would it be an idea to create a PR in the DefinitelyTyped repository? That way we could still use these types without requiring CustomerIO to merge and maintain this.

**Comment by hendrysadrak** [comment]
What's blocking it from getting merged?

**Comment by CanTheAlmighty** [comment]
Well, I haven't used CustomerIO since I made my original PR (I had some other issues, customerio itself is good), so I might come back and move it to DefinitelyTyped

**Comment by nickzelei** [comment]
Thanks for doing this. It's worth mentioning that this only covers the `track.js` module (which is the entrypoint of this module).

There is also the `customerio-node/api` module for when you want to interface with the sendEmail API directly. Trying to figure out how to add that in here as well, or perhaps customerio could simply export it from the entrypoint to make it more accessible.

**Review by webjoaoneto — COMMENTED** [review]
very nice tks

**Comment by mike-engel** [comment]
Hi everyone! First off, thank you to @CanTheAlmighty for taking the time for this PR. We've decided to refactor the entire package to use typescript natively rather than only offer type definitions.

I've published a beta version on npm: `2.1.0-beta.1`. You can install that with the dist tag like so: `npm install customerio-node@beta`.

If you have time, I would love to have y'all try it out and report any bugs you find, if any. We've tested it internally and it should be fully backwards compatible with existing code. If I don't hear anything, we aim to ship it early next week.

Thanks for your patience and your help!

**Comment by mike-engel** [comment]
Closed by #49

**Pull request closed without merging**
