### PR TITLE
fix to export typescript files

### LINKED ISSUE #54: Typings
Hi!
How to use typings of `customerio-node`?

thanks!

### PR DESCRIPTION
**Pull request by nickzelei**
Fixes #54 

# Changes
* Removes unnecessary javascript files
* Updates `package.json` main to point to the dist version of track
* Updates `package.json` to include typings entrypoint
* Retains backwards compat with existing entrypoint so users will notice no change in importing.

# Typescript notes
A future PR should include an `index.ts` file that exports all of the relevant things, including the `api.ts` so that this module can more easily be utilized for sending transactional emails. It's also healthy to have a single entrypoint for a module.
It's important to note though that this would be a breaking change (perhaps a 3.0.0) as it would change how the module is imported.

Current
```
import CIO from 'customerio-node';
```

Future PR:
For tracking
```
import { TrackClient } from 'customerio-node';
```

For API (transactional emails)
```
import { APIClient } from 'customerio-node';
```

### CODE REVIEW

**Review by oleg-koval — DISMISSED** [review]

**Comment by nickzelei** [comment]
@oleg-koval any ideas why the workflow checks aren't running? Not super familiar with how this repo is setup and just assumed they run automatically.

**Comment by oleg-koval** [comment]
no idea as well :) @mike-engel can you please take a look at this issue?

**Comment by mike-engel** [comment]
Thanks for the ping @oleg-koval. I'm not entirely sure why actions aren't running on forks, but we don't have anything in our CI config that would limit where actions can be run. Looking at this [github community post](https://github.community/t/how-to-run-and-enable-github-actions-on-forked-repo-with-github-api/17232/4), however, it looks like actions need to be enabled on the fork in order for them to be run. Let me know if you can try that @nickzelei and if that works or not!

**Comment by nickzelei** [comment]
> Thanks for the ping @oleg-koval. I'm not entirely sure why actions aren't running on forks, but we don't have anything in our CI config that would limit where actions can be run. Looking at this [github community post](https://github.community/t/how-to-run-and-enable-github-actions-on-forked-repo-with-github-api/17232/4), however, it looks like actions need to be enabled on the fork in order for them to be run. Let me know if you can try that @nickzelei and if that works or not!

@mike-engel - that appeared to work on my fork, and the workflow completed! However this PR is still showing that they are waiting. I'm not sure why it isn't being reported here.

**Comment by nickzelei** [comment]
I'm kind of jumping around here, but I think for this PR to make sense and to not break the other imports (API, Region), we would need to change the TS build output to build the javascript to the root of the directory (instead of in dist). This would allow the imports to remain the same.

```
import ApiClient from 'customerio-node/api'`;
```

Where as the current state in this PR is:
```
import ApiClient from 'customerio-node/dist/api';
```

**Comment by mike-engel** [comment]
I'm jumping around as well, but I think I addressed that in my comment in https://github.com/customerio/customerio-node/pull/56#issuecomment-848574919

**Comment by oleg-koval** [comment]
The issue with GH Action can be caused because of branch name `nickzelei:nickzelei/fix-typescript` , still not sure how. @mike-engel is it possible to run it manually like it's described [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)? Thanks!

**Comment by mike-engel** [comment]
Unfortunately our CI isn't configured right now for the `workflow_dispatch` event. Perhaps an empty commit or rebase would trigger it now that the source repo has been configured for actions until we can add that?

**Comment by mike-engel** [comment]
Typings should be fixed with `2.1.1` via #56

**Pull request closed without merging**
